// Venue → city lookup, so the listing can show the town without a city field
// on every concert. Unknown venues simply show no city.
const VENUE_CITY: Record<string, string> = {
  'Glenn Miller Café': 'Stockholm',
  Fasching: 'Stockholm',
  Nefertiti: 'Göteborg',
  'Konserthuset Stockholm': 'Stockholm',
  'Vara Konserthus': 'Vara',
  'Skottvångs Grufva': 'Mariefred',
  'Unity Jazz': 'Göteborg',
  'Playhouse Valand': 'Göteborg',
  'Ystad Sweden Jazz Festival': 'Ystad',
  'Umeå Jazzfestival': 'Umeå',
  'Musikens Hus': 'Göteborg',
  'Slagthusets Teater': 'Malmö',
  Parksnäckan: 'Uppsala',
  'Botaniska trädgården': 'Uppsala',
  Mejeriet: 'Lund',
  'Malmö Live': 'Malmö',
  'Göteborgs Konserthus': 'Göteborg',
  // Stockholm Jazz Festival venues
  'Kulturhuset Stadsteatern': 'Stockholm',
  Allhelgonakyrkan: 'Stockholm',
  'Reimersholme Hotel': 'Stockholm',
  'Moderna Museet': 'Stockholm',
  'Stallet Världens Musik': 'Stockholm',
  Nalen: 'Stockholm',
  Folkoperan: 'Stockholm',
  'Bistro Eker': 'Stockholm',
  Slaktkyrkan: 'Stockholm',
  Vasamuseet: 'Stockholm',
  Scenkonstmuseet: 'Stockholm',
  'KFUM Central': 'Stockholm',
  Aspen: 'Stockholm',
  'Nya Cirkus': 'Stockholm',
  Konserthuset: 'Stockholm',
  'Folkets Hus Kallhäll': 'Kallhäll',
  'Huddinge Kulturhus hos Folkes': 'Huddinge',
  'Scen Messingen': 'Upplands Väsby',
  'Vallentuna Teater': 'Vallentuna',
  // Bangen Jazz & Blues venues (Sandviken)
  'Sandvikens kyrka': 'Sandviken',
  Kanalgården: 'Sandviken',
  Musikverket: 'Sandviken',
  Jansasscenen: 'Sandviken',
  Stadsparken: 'Sandviken',
  Teaterbaren: 'Sandviken',
  // Utopia Jazz & Göteborg venues
  'Utopia Jazz': 'Göteborg',
  'Stora teatern': 'Göteborg',
  'World of Volvo': 'Göteborg',
  // Bohuslän Big Band tour venues
  'Arild Jazzfestival': 'Arild',
  'Kulturhuset Najaden': 'Halmstad',
  'Landskrona teater': 'Landskrona',
  Kulturkvarteret: 'Kristianstad',
  'Skurups folkhögskola': 'Skurup',
  Stadshallen: 'Lund',
  'Östergötlands museum': 'Linköping',
  Messingen: 'Upplands Väsby',
  'Uppsala Konsert & Kongress': 'Uppsala',
  'Gävle konserthus': 'Gävle',
  Culturum: 'Nyköping',
  Dergårdsteatern: 'Lerum',
};

export function cityFor(venue: string): string | undefined {
  return VENUE_CITY[venue];
}
